# Generated by Django 2.2 on 2023-04-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
