# Generated by Django 4.2 on 2023-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles_API', '0003_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
