# Generated by Django 4.2 on 2023-05-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles_API', '0004_userprofile_password_alter_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
